apiVersion: apps/v1
kind: Deployment
metadata:
  name: ginapp1
  labels:
    app: ginapp1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ginapp1
  template:
    metadata:
      annotations:
        ad.datadoghq.com/ginapp1.check_names: '["http_check"]'
        ad.datadoghq.com/ginapp1.init_configs: '[{}]'
        ad.datadoghq.com/ginapp1.instances: |
          [
            {
              "name": "My APM Service",
              "url": "http://%%host%%:%%port%%",
              "timeout": 1
            }
          ]
        ad.datadoghq.com/ginapp1.logs: |
          [
            {
              "source": "go",
              "service": "ginapp1"
            }
          ]
      labels:
        app: ginapp1
        tags.datadoghq.com/env: "sandbox"
        tags.datadoghq.com/service: "ginapp1"
        tags.datadoghq.com/version: "1.0.0"
    spec:
      containers:
        - name: ginapp1
          image: docker.io/seandever376/ginapp1:latest
          ports:
          - containerPort: 8080
          env:
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP