datadog:
  apiKeyExistingSecret: datadog-agent
  clusterName: example.app.agent
  tags: []
  kubelet:
    tlsVerify: false
  kubeStateMetricsEnabled:
    enabled: true
  logs:
    enabled: true
    containerCollectAll: true
  apm:
    enabled: true
    socketEnabled: false
    portEnabled: false
  processAgent:
    enabled: true
    processCollection: false
  systemProbe:
    enableTCPQueueLength: false
    collectDNSStats: false