apiVersion: apps/v1
kind: Deployment
metadata:
  name: ginapp2
  labels:
    app: ginapp2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ginapp2
  template:
    metadata:
      annotations:
        ad.datadoghq.com/ginapp2.check_names: '["http_check"]'
        ad.datadoghq.com/ginapp2.init_configs: '[{}]'
        ad.datadoghq.com/ginapp2.instances: |
          [
            {
              "name": "My APM Service",
              "url": "http://%%host%%:%%port%%",
              "timeout": 1
            }
          ]
        ad.datadoghq.com/ginapp2.logs: |
          [
            {
              "source": "go",
              "service": "ginapp2"
            }
          ]
      labels:
        app: ginapp2
        tags.datadoghq.com/env: "sandbox"
        tags.datadoghq.com/service: "ginapp2"
        tags.datadoghq.com/version: "1.0.0"
    spec:
      containers:
        - name: ginapp2
          image: docker.io/seandever376/ginapp2:latest
          ports:
          - containerPort: 8081
          env:
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP