datadog:
  # apiKey: <DATADOG_API_KEY>
  # appKey: <DATADOG_APP_KEY>
  # If not using secrets, then use apiKey and appKey instead
  apiKeyExistingSecret: datadog-agent
  clusterName: kubernetes-go-sandbox
  tags: []
  # datadog.kubelet.tlsVerify should be `false` on kind and minikube
  # to establish communication with the kubelet
  kubelet:
    tlsVerify: false
  kubeStateMetricsEnabled:
    enabled: true
  logs:
    enabled: true
    containerCollectAll: true
  apm:
    socketEnabled: false
    portEnabled: true
  processAgent:
    enabled: true
    processCollection: false
  systemProbe:
    enableTCPQueueLength: false
    collectDNSStats: false